#!/usr/bin/env ruby

require './xmlparser'
require './views/kudos'
require './pagerank'

programmers = Programmers.new(retrieve_programmers_with_kudos(ARGV[0]))

calculator = PageRankCalculator.new programmers
calculator.calculate_pagerank

puts Kudos.new(programmers.programmers).render
